src/vash_remont/gallery/urls.py
from django.conf.urls import url
from .views import get_galleries

urlpatterns = [
    url(r'^$', get_galleries, name="get_galleries"),
]

src/vash_remont/reviews/urls.py
from django.conf.urls import url
from .views import create_reviews

urlpatterns = [
    url(r'^create$', create_reviews, name="create_reviews"),
]

src/vash_remont/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import home_page, send_application

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name="home"),
    url(r'^send_application$', send_application, name="send_application"),

    url(r'^gallery/', include('vash_remont.gallery.urls', namespace="gallery")),
    url(r'^video/', include('vash_remont.video.urls', namespace="video")),
    url(r'^reviews/', include('vash_remont.reviews.urls', namespace="reviews")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/vash_remont/video/urls.py
from django.conf.urls import url
from .views import get_video

urlpatterns = [
    url(r'^$', get_video, name="get_video"),
]

src/vash_remont/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    phone_number = models.CharField(
        verbose_name="Номер телефона",
        max_length=128
    )

src/vash_remont/gallery/models.py
from django.db import models


class BaseImage(models.Model):
    class Meta:
        abstract = True
        ordering = "-datetime",

    image = models.ImageField(
        verbose_name="Фотография",
        upload_to='gallery/',
    )

    datetime = models.DateTimeField(auto_now_add=True, blank=True)


class Gallery(models.Model):
    class Meta:
        verbose_name_plural = "Галерея"
        verbose_name = "Галерея"
        ordering = "-my_order",

    name = models.CharField(
        verbose_name="Название Галереи",
        max_length=254,
        default="",
    )

    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    datetime = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.name


class Image(BaseImage):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)

src/vash_remont/reviews/models.py
from django.db import models
from datetime import datetime

APPROVED = '1'
NOT_APPROVED = '0'

STATE_REVIEW_CHOICES = (
    (NOT_APPROVED, 'Не одобрен'),
    (APPROVED, 'Одобрен'),
)


class Review(models.Model):
    class Meta:
        verbose_name_plural = "Отзывы"
        verbose_name = "Отзыв"
        ordering = "-datetime",

    name_user = models.CharField(
        verbose_name="Имя пользователя",
        max_length=256,
    )

    review_text = models.TextField(
        verbose_name="Текст отзыва",
        max_length=2048,
    )

    state = models.CharField(
        max_length=2,
        choices=STATE_REVIEW_CHOICES,
        default=NOT_APPROVED,
    )

    datetime = models.DateTimeField(
        verbose_name="Дата и время отзыва",
        default=datetime.now,
    )

    def __str__(self):
        return self.name_user + " (" + str(self.datetime) + ")"

src/vash_remont/settings_site/models.py
from django.db import models


class SettingsSite(models.Model):
    class Meta:
        verbose_name_plural = "Настройки сайта"
        verbose_name = "Настройки сайта"

    email = models.EmailField(
        verbose_name="Электронная почта"
    )

    number_phone_one = models.CharField(
        verbose_name="Номер телефона 1",
        max_length=60
    )

    number_phone_two = models.CharField(
        verbose_name="Номер телефона 2",
        max_length=60,
        blank=True,
        null=True,
    )

    youtube_link = models.CharField(
        verbose_name="Ссылка на youtube",
        max_length=9000
    )

    vk_link = models.CharField(
        verbose_name="Ссылка на VK",
        max_length=9000
    )

    twitter_link = models.CharField(
        verbose_name="Ссылка на twitter",
        max_length=9000
    )

    google_plus_link = models.CharField(
        verbose_name="Ссылка на google plus",
        max_length=9000
    )

src/vash_remont/video/models.py
from django.db import models


class Video(models.Model):
    class Meta:
        verbose_name_plural = "Видео"
        verbose_name = "Видео"
        ordering = "-my_order",

    name = models.CharField(
        verbose_name="Название видео",
        max_length=254,
    )

    iframe = models.TextField(
        verbose_name="iframe видео",
        help_text="Чтобы вставить iframe, нужно на youtube под видео нажать на 'поделиться', затем нажать на встроить,"
                  " и скопировать тег iframe.",
        max_length=9000,
    )

    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    datetime = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.name

src/vash_remont/accounts/views.py
from django.shortcuts import render

# Create your views here.

src/vash_remont/gallery/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from .models import Gallery


def get_galleries(request):
    gallery_html_data = render_to_string(
        "modal/gallery/gallery_data.html",
        {"galleries": Gallery.objects.all()}
    )

    return JsonResponse({
        "gallery_html_data": gallery_html_data
    })

src/vash_remont/reviews/views.py
from django.http import JsonResponse
from django.core.mail import send_mail
from .models import Review
from django.conf import settings


def create_reviews(request):
    initials = request.GET['initials']
    review = request.GET['review']

    Review.objects.create(
        name_user=initials,
        review_text=review
    )

    status_send = send_mail(
        'Отзыв на сайт', 'Инициалы: ' + initials + "\n\nОтзыв: " + review,
        settings.EMAIL_HOST_USER,
        [settings.EMAIL_HOST_USER]
    )

    if status_send == 1:
        return JsonResponse({
            "success": True,
        })
    else:
        return JsonResponse({
            "success": False,
        })

src/vash_remont/settings_site/views.py
from django.shortcuts import render

# Create your views here.

src/vash_remont/video/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from .models import Video


def get_video(request):
    gallery_html_data = render_to_string(
        "modal/video/video_data.html",
        {"videos": Video.objects.all()}
    )

    return JsonResponse({
        "video_html_data": gallery_html_data
    })

src/vash_remont/views.py
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import render

from vash_remont.gallery.models import Gallery, Image
from vash_remont.video.models import Video
from vash_remont.reviews.models import Review, APPROVED

from vash_remont.settings_site.models import SettingsSite
from django.conf import settings


def home_page(request):

    images = Image.objects.order_by('?').all()[:4]
    galleries = Gallery.objects.all()

    reviews = Review.objects.filter(state=APPROVED).all()
    main_reviews = reviews.order_by('?')[:3]

    settings_site = SettingsSite.objects.first()

    if settings_site is None:
        settings_site = {
            "email": "",
            "number_phone": "",
            "youtube_link": "#",
            "vk_link": "#",
            "twitter_link": "#",
            "google_plus_link": "#"
        }

    return render(request, "index.html", {
        "main_images": images,
        "galleries": galleries,
        "count_videos": Video.objects.count(),

        "main_reviews": main_reviews,
        "reviews": reviews,

        "settings_site": settings_site
    })


def send_application(request):
    initials = request.GET['initials']
    phone = request.GET['phone']

    status_send = send_mail(
        'Заявка на консультацию', 'Инициалы: ' + initials + "\nНомер телефона: " + phone,
        settings.EMAIL_HOST_USER,
        [settings.EMAIL_HOST_USER]
    )

    if status_send == 1:
        return JsonResponse({
            "success": True,
        })
    else:
        return JsonResponse({
            "success": False,
        })

templates/base.html
{% load staticfiles %}
{% load compress %}
{% load i18n %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png'%}"/>

        <title>{% block title %}{% endblock %}</title>
        {% compress css %}
            <link href="{% static 'packages/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'packages/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
            <link href="{% static 'packages/fancybox/jquery.fancybox.min.css' %}" rel="stylesheet">
            <link href="{% static 'styles/header.sass' %}" rel="stylesheet" type="text/x-sass" />
            <link href="{% static 'styles/footer.sass' %}" rel="stylesheet" type="text/x-sass" />
            <link href="{% static 'styles/modal/main.sass' %}" rel="stylesheet" type="text/x-sass" />
            <link href="{% static 'styles/modal/gallery.sass' %}" rel="stylesheet" type="text/x-sass" />
            <link href="{% static 'styles/modal/application.sass' %}" rel="stylesheet" type="text/x-sass" />
            <link href="{% static 'styles/modal/reviews.sass' %}" rel="stylesheet" type="text/x-sass" />
            <link href="{% static 'styles/modal/video.sass' %}" rel="stylesheet" type="text/x-sass" />
            {% block styles %}
            {% endblock %}
        {% endcompress %}

        {% block head_js %}

        {% endblock %}

    </head>

    <body>

        {% include "header.html" %}

        {% csrf_token %}
        {% block content %}
        {% endblock %}

        {% include "modal/gallery/gallery_modal.html" %}
        {% include "modal/application.html" %}
        {% include "modal/reviews/write_reviews.html" %}
        {% include "modal/reviews/all_reviews.html" %}

        {% if count_videos > 0 %}
            {% include "modal/video/video_modal.html" %}
        {% endif %}


        {% if page_history is not True %}
            {% include "footer.html" %}
        {% endif %}

        {% compress js %}
            <script src="{% static 'packages/jquery-3.2.1.min.js' %}"></script>
            <script src="{% static 'packages/bootstrap4/js/bootstrap.min.js' %}"></script>
            <script src="{% static 'packages/fancybox/jquery.fancybox.min.js' %}"></script>
            <script src="{% static 'packages/anchor.min.js' %}"></script>
            <script src={% static 'js/main.js' %}></script>
            <script src={% static 'js/menu.js' %}></script>
            <script src={% static 'js/open_gallery.js' %}></script>
            <script src={% static 'js/application.js' %}></script>
            <script src={% static 'js/create_reviews.js' %}></script>
            <script src={% static 'js/open_video.js' %}></script>
            {% block js %}
            {% endblock %}
        {% endcompress %}
    </body>
</html>

templates/footer.html
{% load staticfiles %}

<footer>
    <div class="container-fluid">
        <div class="container">
            <div class="social-networks footer-data">
                <a href="{{ settings_site.vk_link }}" target="_blank">
                    <img class="social-img first-social-img" src={% static "images/vk.png" %}>
                </a>
                <a href="{{ settings_site.youtube_link }}" target="_blank">
                    <img class="social-img" src={% static "images/yutube.png" %}>
                </a>
                <a href="{{ settings_site.twitter_link }}" target="_blank">
                    <img class="social-img" src={% static "images/tw.png" %}>
                </a>
                <a href="{{ settings_site.google_plus_link }}" target="_blank">
                    <img class="social-img" src={% static "images/gplus.png" %}>
                </a>
            </div>
            <div class="all-link footer-data">
                <ul class="menu-footer menu-anchor">
                    <li class="item item-footer" data-type="item-main"><a class="items-menu" href="#main-section">Главная</a></li>
                    <li class="item item-footer" data-type="item-advantages"><a class="items-menu" href="#advantages-section">О компании</a></li>
                    <li class="item item-footer" data-type="item-services"><a class="items-menu" href="#services-section">Услуги</a></li>
                    <li class="item item-footer" data-type="item-our-works"><a class="items-menu" href="#our-works-section">Работы</a></li>
                    <li class="item item-footer" data-type="item-reviews-section"><a class="items-menu" href="#reviews-section">Отзывы</a></li>
                </ul>
            </div>
            <div class="logo-phone footer-data">
                <a class="link-mobile-logo" href="/">
                    <img class="logo-footer" src={% static "images/logo.png" %}>
                </a>
                <a class="phone-footer" href="tel:{{ settings_site.number_phone_one }}">{{ settings_site.number_phone_one }}</a>
                <a class="phone-footer phone-footer-two" href="tel:{{ settings_site.number_phone_two }}">{{ settings_site.number_phone_two }}</a>
                <a class="email-footer" href="mailto:{{ settings_site.email }}">{{ settings_site.email }}</a>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load staticfiles %}

<header>
    <div class="container-fluid">
        <div class="container">
            <a href="/">
                <img class="img-responsive logo" src="{% static "images/logo.png" %}">
            </a>

            <ul class="menu-desktop menu-anchor">
                <li class="item active item-main"><a class="items-menu" href="#main-section">Главная</a></li>
                <li class="item item-advantages"><a class="items-menu" href="#advantages-section">О компании</a></li>
                <li class="item item-services"><a class="items-menu" href="#services-section">Услуги</a></li>
                <li class="item item-our-works"><a class="items-menu" href="#our-works-section">Работы</a></li>
                <li class="item item-reviews-section"><a class="items-menu" href="#reviews-section">Отзывы</a></li>
            </ul>
            <a class="header-desktop-phone" href="tel:{{ settings_site.number_phone_one }}">{{ settings_site.number_phone_one }}</a>
            <a class="header-desktop-phone" href="tel:{{ settings_site.number_phone_two }}">{{ settings_site.number_phone_two }}</a>
            <i class="fa fa-list" aria-hidden="true"></i>
            <i class="fa fa-times none" aria-hidden="true"></i>
        </div>
        <ul class="menu-mobile none menu-anchor">
            <li class="item-mobile active item-main"><a class="items-menu" href="#main-section">Главная</a></li>
            <li class="item-mobile item-advantages"><a class="items-menu" href="#advantages-section">О компании</a></li>
            <li class="item-mobile item-services"><a class="items-menu" href="#services-section">Услуги</a></li>
            <li class="item-mobile item-our-works"><a class="items-menu" href="#our-works-section">Работы</a></li>
            <li class="item-mobile item-reviews-section"><a class="items-menu" href="#reviews-section">Отзывы</a></li>
            <a class="phone-mobile" href="tel:{{ settings_site.number_phone_one }}">{{ settings_site.number_phone_one }}</a>
            <a class="phone-mobile" href="tel:{{ settings_site.number_phone_two }}">{{ settings_site.number_phone_two }}</a>
        </ul>
    </div>
</header>

templates/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Ваш ремонт{% endblock %}

{% block styles %}
    <link href="{% static 'styles/base.sass' %}" rel="stylesheet" type="text/x-sass" />
    <link href="{% static 'styles/index/main.sass' %}" rel="stylesheet" type="text/x-sass" />
    <link href="{% static 'styles/index/advantages.sass' %}" rel="stylesheet" type="text/x-sass" />
    <link href="{% static 'styles/index/order_of_work.sass' %}" rel="stylesheet" type="text/x-sass" />
    <link href="{% static 'styles/index/services.sass' %}" rel="stylesheet" type="text/x-sass" />
    <link href="{% static 'styles/index/to_order.sass' %}" rel="stylesheet" type="text/x-sass" />
    <link href="{% static 'styles/index/our_works.sass' %}" rel="stylesheet" type="text/x-sass" />
    <link href="{% static 'styles/index/reviews.sass' %}" rel="stylesheet" type="text/x-sass" />
    {{ block.super }}
{% endblock %}

{% block js %}
    {{ block.super }}
{% endblock %}

{% block content %}
    {% include "index_div/main.html" %}
    {% include "index_div/advantages.html" %}
    {% include "index_div/order_of_work.html" %}
    {% include "index_div/services.html" %}
    {% include "index_div/to_order.html" %}
    {% include "index_div/our_works.html" %}
    {% include "index_div/reviews.html" %}
{% endblock %}

templates/index_div/advantages.html
{% load staticfiles %}
<div id="advantages-section" class="anchor"></div>
<section class="advantages container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 content-block">
                <h3><span>Наши</span> преимущества</h3>

                <div class="advantage">
                    <img class="img-responsive" src="{% static "images/8_years.png" %}">
                    <p>Более 8 лет<br>на рынке</p>
                </div>

                <div class="advantage">
                    <img class="img-responsive" src="{% static "images/timing.png" %}">
                    <p>Соблюдение<br>сроков</p>
                </div>

                <div class="advantage">
                    <img class="img-responsive" src="{% static "images/great_quality.png" %}">
                    <p>Отличное<br>качество</p>
                </div>

                <div class="advantage">
                    <img class="img-responsive" src="{% static "images/high_service.png" %}">
                    <p>Высокий<br>сервис</p>
                </div>

                <div class="advantage advantage-last-mobile">
                    <img class="img-responsive" src="{% static "images/pleasant_discounts.png" %}">
                    <p>Приятные<br>скидки</p>
                </div>
            </div>
        </div>
    </div>
</section>

templates/index_div/main.html
<div id="main-section" class="anchor"></div>
<section class="main-div container-fluid">
    <div class="main-substrate"></div>
    <div class="container">
        <h3>"Ваш ремонт"</h3>
        <p>полный спектр услуг<br>по ремонту квартир<br> в Новосибирске</p>
        <button class="order-consultation-btn" data-toggle="modal" data-target="#modalApplication">Заказать консультацию</button>
    </div>
</section>

templates/index_div/order_of_work.html
{% load staticfiles %}

<section class="order-of-work">
    <div class="container-fluid">
        <div class="order-of-work-substrate"></div>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 content-block">
                    <div class="order-of-work-content">
                        <h3>Порядок <span>работ</span></h3>

                        <ul>
                            <li><i class="fa fa-circle" aria-hidden="true"></i> Звонок</li>
                            <li><i class="fa fa-circle" aria-hidden="true"></i> Назначение встречи</li>
                            <li><i class="fa fa-circle" aria-hidden="true"></i> Составление сметы</li>
                            <li><i class="fa fa-circle" aria-hidden="true"></i> Подписание договора</li>
                            <li><i class="fa fa-circle" aria-hidden="true"></i> Закупка материала</li>
                            <li><i class="fa fa-circle" aria-hidden="true"></i> Ремонт</li>
                            <li class="last-li"><i class="fa fa-circle" aria-hidden="true"></i> Подписание акта<br>выполненных работ</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/index_div/our_works.html
{% load staticfiles %}
{% load thumbnail %}

<div id="our-works-section" class="anchor"></div>
<section class="our-works">
    <div class="container-fluid">
        <div class="order-of-work-substrate"></div>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 content-block">
                    <div class="our-works-content">
                        <h3>Наши <span>работы</span></h3>

                        {% if main_images|length >= 4 %}
                            <div class="row row-img-works">
                                {% for image_obj in main_images %}
                                    <div class="image-div
                                        {% if forloop.counter0 == 0 or forloop.counter0 == 1 %}
                                            first-image-div
                                        {% endif %}
                                    ">
                                        <a data-fancybox="main-img" data-options='{"caption" : "{{ image_obj.gallery.name }}"}' href="{{ image_obj.image.url }}">
                                            {% thumbnail image_obj.image 563x320 upscale as image %}
                                            <img src="{{ image.url }}" width="{{ image.width }}" height="{{ image.height }}" class="img-thumbnail thumbnail">
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>

                            {% if galleries|length > 0 %}
                                <div class="row row-btn">
                                    <div class="btn-div
                                        {% if count_videos == 0 %}
                                            btn-none-video
                                        {% endif %}
                                        ">
                                        <button id="open-gallery" data-toggle="modal" data-target="#modalGallery">
                                            <i class="fa fa-picture-o" aria-hidden="true"></i> Посмотреть фото работ
                                        </button>
                                    </div>

                                    {% if count_videos > 0 %}
                                        <div class="btn-div btn-div-video">
                                            <button class="btn-modal-video" id="open-video" data-toggle="modal" data-target="#modalVideo">
                                                <i class="fa fa-play" aria-hidden="true"></i> Посмотреть видео работ
                                            </button>
                                        </div>
                                    {% endif %}
                                </div>
                            {% endif %}

                        {% else %}
                            <p class="works-is-not">В ближайшее время мы добавим примеры работ</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/index_div/reviews.html
{% load staticfiles %}

<div id="reviews-section" class="anchor"></div>
<section class="reviews">
    <div class="container-fluid">
        <div class="reviews-substrate"></div>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 content-block">
                    <div class="reviews-content">
                        <h3><span>Отзывы</span> о нас</h3>

                        <div class="row row-reviews">
                            {% if main_reviews|length >= 3 %}
                                {% for review in main_reviews%}
                                    <div class="review
                                        {% if forloop.counter0 == 0 %}
                                            review-first
                                        {% endif %}
                                    ">
                                        <div class="desktop-data">
                                            <div class="review-text">
                                                <p>{{ review.review_text }}</p>
                                            </div>
                                            <div class="user-info">
                                                <hr>
                                                <p class="date-review">{{ review.datetime|date:"d.m.Y H:i" }}</p>
                                                <p class="name-people-review">{{ review.name_user }}</p>
                                                <img class="people-img" src={% static "images/people.png" %}>
                                            </div>
                                        </div>
                                        <div class="mobile-data">
                                            <div class="user-info-mobile">
                                                <p>{{ review.name_user }}</p>
                                            </div>

                                            <div class="review-text-mobile">
                                                <p>{{ review.review_text }}</p>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="action-reviews">
                            {% if reviews|length > 3 %}
                                <button class="view-review text-center" data-toggle="modal" data-target="#modalAllReviews">Посмотреть все отзывы</button>
                            {% endif %}
                            <button class="write-review" data-toggle="modal" data-target="#modalWriteReviews">Написать отзыв</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/index_div/services.html
{% load staticfiles %}

<div id="services-section" class="anchor"></div>
<section class="services container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 content-block">
                <h3><span>Наши</span> услуги</h3>

                <div class="service">
                    <p>Ремонт<br>"под ключ"</p>
                    <img class="img-responsive" src="{% static "images/turnkey_repair.png" %}">
                </div>

                <div class="service">
                    <p>Ремонт<br>"по частям"</p>
                    <img class="img-responsive" src="{% static "images/repair_parts.png" %}">
                </div>

                <div class="service">
                    <p>Подбор<br>материалов</p>
                    <img class="img-responsive" src="{% static "images/selection_materials.png" %}">
                </div>
            </div>
        </div>
    </div>
</section>

templates/index_div/to_order.html
{% load staticfiles %}

<section class="to-order">
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="to-order-content">
                        <p>оставить заявку на бесплатную<br>консультацию и составление сметы</p>
                        <button data-toggle="modal" data-target="#modalApplication">Заказать</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/modal/application.html
<div class="modal fade" data-backdrop="static" id="modalApplication" tabindex="-1" role="dialog" aria-labelledby="modalApplicationLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">Заказать <span>консультацию</span></h3>
            <button type="button" class="close modal-close modal-close-application" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body modal-body-application">
            <div class="form-data">
                <form id="application-form">
                    <p class="title-input">Введите инициалы:</p>
                    <input type="text" id="initials" name="initials" placeholder="Ф.И.О" value="">
                    <p class="title-input">Введите номер телефона:</p>
                    <input type="tel" id="phone" name="phone" placeholder="Номет телефона" value="">
                    <p class="status-data"></p>
                    <button>Заказать</button>
                </form>
            </div>
        </div>
    </div>
  </div>
</div>

templates/modal/gallery/gallery_data.html
{% load staticfiles %}
{% load thumbnail %}

{% for gallery in galleries %}
    <div class=" row row-title-gallery
    {% if forloop.counter0 == 0 %}
         row-title-gallery-first
    {% endif %}
    ">
        <p class="name-gallery">{{ gallery.name }}</p>
    </div>
    <div class="row row-gallery">
        {% for image_obj in gallery.image_set.all %}
            <div class="gallery-img">
                <a data-fancybox="gallery-{{ gallery.id }}" data-options='{"caption" : "{{ gallery.name }}"}' href="{{ image_obj.image.url }}">
                    {% thumbnail image_obj.image 186x106 upscale as image %}
                    <img src="{{ image.url }}" width="{{ image.width }}" height="{{ image.height }}" class="img-thumbnail gallery-img-thumbnail">
                </a>
            </div>
        {% endfor %}
    </div>
{% endfor %}

templates/modal/gallery/gallery_modal.html
{% load staticfiles %}
{% load thumbnail %}

<div class="modal fade" data-backdrop="static" id="modalGallery" tabindex="-1" role="dialog" aria-labelledby="modalGalleryLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">Наши <span>работы</span></h3>
            <button type="button" class="close modal-close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body modal-body-gallery">
            <div class="work-items gallery-items">
                <i class="fa fa-cog fa-spin fa-fw"></i>
            </div>
        </div>
    </div>
  </div>
</div>

templates/modal/video/video_data.html
{% for video in videos %}
    <div class="div-video-items">
        {{ video.iframe|safe}}
    </div>
{% endfor %}